#!/usr/bin/env python3
import pathlib
import shutil
import sys


def get_root(cwd=None):
    if cwd is None:
        cwd = pathlib.Path.cwd()
    if (cwd / "src").exists():
        return cwd
    if not cwd.parent:
        return None
    return get_root(cwd.parent)


def copy_pkgs(root_path):
    vendor_pkgs = root_path / "vendor" / "pkg"
    gb_pkgs = root_path / "pkg"
    if vendor_pkgs.exists():
        shutil.rmtree(str(vendor_pkgs))
    for platform in gb_pkgs.glob('*/*'):
        target_folder = vendor_pkgs / (platform.parts[-2] + '_' + platform.parts[-1])
        shutil.copytree(str(platform), str(target_folder))


def main():
    root = get_root()
    if not root:
        print("You are not inside a gb project!")
        sys.exit(1)
    copy_pkgs(root)


if __name__ == '__main__':
    main()
